name: Force Replace All Resources

on:
  workflow_dispatch:

jobs:
  force-replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Force replace all Cloudflare resources
        uses: hashicorp/terraform-cdk-action@v11.0.2
        with:
          cdktfVersion: 0.20.11
          terraformVersion: 1.10.5
          stackName: cdktf
          terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          mode: auto-approve-apply
          workingDirectory: ./
          commentOnPr: false
          updateComment: false
          suppressOutput: false
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}